[project]
name = "cnn-project"
version = "0.1.0"
description = "Python GUI classes CNN demo"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "keras>=3.11.3",
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pyside6>=6.10.0",
    "scikeras>=0.13.0",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]

[tool.setuptools.package-dir]
"" = "."
"src" = "src"
"src.cnnpy" = "src/cnnpy"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
